language: php

php:
  - '7.2'
  - '7.3'
  - nightly

services:
  - docker

before_install:
  - docker-compose up -d
  - docker-compose -f docker-compose.yml run wait

before_script:
  - mkdir -p build/logs
  - ls -al

install:
  - travis_retry composer install --no-interaction
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - php php-coveralls.phar --version

script:
  - ./vendor/bin/grumphp run

after_success:
  - travis_retry php php-coveralls.phar -v
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - vendor
    - $HOME/.cache/composer
    - /var/lib/docker